### ISSUE TITLE
[usage] make windows as guest of cuckoo?

### ISSUE THREAD

**Issue by jm18919** [jgajek/cuckoo-docker#1]
Hello, I am pretty new to docker.
What your repository provides is the host of cuckoo, right?
Say, I want to analyze a virus in Win, I have to configure a Win guest installed with cuckoo agent, and link this Win guest to your cuckoo-docker?

**Comment by jgajek** [comment]
Yes, and the Win guest should be hosted on a different physical host (e.g. a VMware ESXi host).  I have never been able to get it to work when the VM host is on the same machine as the Cuckoo docker container.
